#!/usr/bin/bash

ln -sf ~/dotfiles/.config/nvim/init.vim ~/.vimrc
ln -sf ~/dotfiles/.vim ~/
ln -sf ~/dotfiles/.bash_profile ~/
ln -sf ~/dotfiles/.config/* ~/.config
ln -sf ~/dotfiles/.ripgreprc ~/
ln -sf ~/dotfiles/.gitconfig ~/
ln -sf ~/dotfiles/bin ~/

if [ $SPIN ]; then
  # remove outdated nodejs
  sudo rm -f /usr/local/bin/node /usr/local/bin/nodejs

  sudo apt-get install -y fzf ripgrep nodejs rsync silversearcher-ag

  # install vim plug
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  # install vim plugins
  vim -u ~/.vim/plugins.vim -c ':PlugInstall | qa!'
fi

