#!/usr/bin/bash

ln -sf ~/dotfiles/.bash_profile ~/
ln -sf ~/dotfiles/.config/* ~/.config
ln -sf ~/dotfiles/.ripgreprc ~/
ln -sf ~/dotfiles/.gitconfig ~/

if [ $SPIN ]; then
  ln -sf ~/dotfiles/.zshrc.spin ~/.zshrc

  sudo apt-get install -y fzf ripgrep rsync silversearcher-ag

  # install vim plug
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  # install vim plugins
  nvim -u ~/.config/nvim/plugins.vim -c ':PlugInstall | qa!'
  nvim -c ':CocInstall coc-rust-analyzer | qa!'

  git config --global user.email "michael.cooney@shopify.com"
fi

