#!/usr/bin/bash

ln -sf ~/dotfiles/.vimrc ~/
ln -sf ~/dotfiles/.bash_profile ~/
ln -sf ~/dotfiles/.config/* ~/.config
ln -sf ~/dotfiles/.ripgreprc ~/
ln -sf ~/dotfiles/.gitconfig ~/
ln -sf ~/dotfiles/bin ~/

# install vim plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

#if [ $SPIN ]; then
#  sudo rm -f /usr/local/bin/node /usr/local/bin/nodejs
#  sudo apt-get install -y fzf ripgrep nodejs
#fi

